### ISSUE TITLE
service install works, but gives strange error

### ISSUE THREAD

**Issue by pablomaurer** [alykoshin/nssm#6]
Just tried your lib first time ;) The installation works (tested with my code and your example file) but gives the following error:

``` js
installed Error: 摁業楮瑳慲潴⁲捡散獳椠⁳敮摥摥琠⁯湩瑳污⁬⁡敳癲捩⹥഍
    at C:\projekte\ai\electron-ner\dist\win-unpacked\resources\app\node_modules\nssm\lib\index.js:72:19
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by alykoshin** [comment]
Can you, please, provide more info. Which service are you installing, code snippet etc. What returns `nssm` if started from command line. What may mean this mysterious hieroglyphic text (I have no idea, I suggest, it is returned by the OS). 
I just made clean project using latest `nssm` package and got no errors.

**Comment by pablomaurer** [comment]
- Windows 10 / Node Version 5.5.0
- I downloaded your repository as `.zip` entpacked it.
- Opened cmd and went into your examples dir
- Did run `node install.js`
- I think nssm pops up for a second and closes again -> which also are this hieroglyphic (already had this error when playing with nssm, it was also because i opened nssm as gui)
- Services is installed, altough the popping and hieroglyphics

**Comment by alykoshin** [comment]
I think, you need to try to set the full path to `nssm.exe` when calling the constructor:

```
//var options = { nssmExe: 'nssm.exe' }; // default
var options = { nssmExe: 'c:\some_long_path\nssm.exe' }; 
```

what if you run `nssm get start` inside `examples` directory ?

**Comment by pablomaurer** [comment]
Did you mean? `nssm get test Start`:

```
C:\Users\me\Downloads\nssm-master\nssm-master\examples>nssm get test Start
SERVICE_AUTO_START
```

I also changed the path, but behaves exactly the same:

``` js
var path = require('path');
var nssmPath = path.join('C:/Users/me/Downloads/nssm-master/nssm-master/examples', 'nssm.exe');
var options = { nssmExe: nssmPath };
```

Interessting that you don't have this issue..
Which os and node version do you have?

---

My current own working implementation looks like this:
I used it with the [sudo-prompt package](https://github.com/jorangreef/sudo-prompt)

``` js
var sudo = require('sudo-prompt');
var installCommand = nssm + ' install ' + self.serviceName  + ' "' + self.nodePath + '" "' + self.nodeScriptWithArg + '"';

function runAsAdmin(command) {
        return new Promise(function (resolve, reject) {
            console.warn('running command as admin: ', command);
            sudo.exec(command, {name: 'test'}, function(error, stdout, stderr) {

                error && console.log(error);
                stdout && console.log(stdout);
                stderr && console.log(stderr);

                if (error || stderr) {
                    reject({sudoPromptError: error, commandError: stderr});
                } else {
                    resolve(stdout);
                }
            });
        });
    }
```

**Comment by alykoshin** [comment]
Windows 2008 R2 Standard 64 bit

```
C:\nssm\test>node -v
v4.2.6
C:\nssm\test>nssm -v
NSSM: The non-sucking service manager
Version 2.24 64-bit, 2014-08-31
```

**Comment by MichaelLeeHobbs** [comment]
```childProcess.execFile(options.nssmExe, args, { encoding: 'utf16le' }, function(error, stdout, stderr) {```

The ```{ encoding: 'utf16le' }``` is the issue. Not sure why you are doing that? If you have a specific reason then you should change it to ```{ encoding: options.encoding || 'utf8' }``` as utf8 to my knowledge is the standard in most of the world and where it's not the standard they are used to dealing with utf8.

**Comment by gustavocipriani** [comment]
@alykoshin any chance you can release a new version containing this fix? I'm also facing the exact same issue.
